
name: synth-matereals

dependencies:
  - pip
  - numpy
  - pandas
  - matplotlib
  - cython
  - torchvision>=0.6.0
  - scipy
  - onnx
  - onnxruntime
  - pip:
    - pycocotools-windows
    - timm
    - opencv-python
    - submitit
    - cityscapesscripts
    - torch>=1.5.0
    # - git+https://github.com/cocodataset/panopticapi.git#egg=panopticapi